name: qr_code_scanner
description: QR code scanner that can be embedded inside flutter. It uses zxing in Android and MTBBarcode scanner in iOS.
version: 0.3.2
homepage: https://juliuscanute.com
repository: https://github.com/juliuscanute/qr_code_scanner

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.2

flutter:
  plugin:
    platforms:
      android:
        package: net.touchcapture.qr.flutterqr
        pluginClass: FlutterQrPlugin
      ios:
        pluginClass: FlutterQrPlugin
